In [1]:
import xarray as xr
import matplotlib.pyplot as plt
import numpy as np

### Maths Servers

In [2]:
# import sys
# sys.path.append('/home/links/ct715/eddy_feedback/')
# import functions.eddy_feedback as ef 
# import functions.data_wrangling as data 

# ## JRA55
# # import dataset for maths servers
# jra = xr.open_mfdataset('/home/links/ct715/data_storage/reanalysis/srip_datasets/jra55_TEM_ubar_div1.nc') 
# era = xr.open_mfdataset('/home/links/ct715/data_storage/reanalysis/srip_datasets/era_int_TEM_ubar_div1.nc')
# ncep = xr.open_mfdataset('/home/links/ct715/data_storage/reanalysis/srip_datasets/ncep_ncar_TEM_ubar_div1.nc')

### JASMIN Servers

In [3]:
import sys
sys.path.append('/home/users/cturrell/documents/eddy_feedback')
import functions.eddy_feedback as ef 
import functions.data_wrangling as data 

## JRA55
# import dataset for maths servers
jra = xr.open_mfdataset('/gws/nopw/j04/arctic_connect/cturrell/reanalysis_data/srip_datasets/jra55_TEM_ubar_div1.nc') 
era = xr.open_mfdataset('/gws/nopw/j04/arctic_connect/cturrell/reanalysis_data/srip_datasets/era_int_TEM_ubar_div1.nc')
ncep = xr.open_mfdataset('/gws/nopw/j04/arctic_connect/cturrell/reanalysis_data/srip_datasets/ncep_ncar_TEM_ubar_div1.nc')

# Figure 6b

## JRA55

In [4]:
r_jra = ef.calculate_efp_latitude(jra, level_mean=False, which_div1='div1_pr')

In [5]:
# plt.figure()

# for i in range(len(r_jra.level)):
#     lw=1.
#     if i == 1: lw=2.

#     plt.plot(r_jra.lat.values, r_jra[i,:].values, linewidth=lw, label=f'{r_jra.level[i].values.astype(np.int64)} hPa')
    
# plt.plot(r_jra.lat.values, r_jra.mean('level').values, color='k', linewidth=2, label='mean')

# plt.xlabel('Latitude ($^\\circ N$)')
# plt.ylabel('$corr^2(\\overline{u}, \\nabla_{\\phi} F_{\\phi})$')
# plt.title('Chosen pressure level comparison')
# plt.legend()

# plt.show() 

### Eddy Feedback Parameter

In [6]:
efp_mean_jra = ef.calculate_efp(jra, which_div1='div1_pr').round(3)
efp_jra = ef.calculate_efp(jra, take_level_mean=False, which_div1='div1_pr')
efp_jra

<xarray.DataArray (level: 6)>
array([0.33908073, 0.44989399, 0.47771496, 0.51836692, 0.50527348,
       0.39981183])
Coordinates:
  * level    (level) float32 600.0 500.0 400.0 300.0 250.0 200.0

In [7]:
levels_dict_jra = {}
for i in range(len(r_jra.level.values)):

    levels_dict_jra[f'efp_{efp_jra.level.values[i].astype(np.int64)}hPa'] = efp_jra.values[i].round(3)

print(f'The EFP mean: {efp_mean_jra}')
print()

for key in levels_dict_jra:
    print(f'The EFP for {key}: {levels_dict_jra[key]}')
    print()

The EFP mean: 0.448

The EFP for efp_600hPa: 0.339

The EFP for efp_500hPa: 0.45

The EFP for efp_400hPa: 0.478

The EFP for efp_300hPa: 0.518

The EFP for efp_250hPa: 0.505

The EFP for efp_200hPa: 0.4



### Southern Hemisphere

In [8]:
r_jra_sh = ef.calculate_efp_latitude(jra, level_mean=False, which_div1='div1_pr', calc_south_hemis=True)
efp_mean_jra_sh = ef.calculate_efp(jra, calc_south_hemis=True, which_div1='div1_pr').round(3)
efp_jra_sh = ef.calculate_efp(jra, take_level_mean=False, calc_south_hemis=True, which_div1='div1_pr')

/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)


In [9]:
levels_dict_jra_sh = {}
for i in range(len(r_jra_sh.level.values)):

    levels_dict_jra_sh[f'efp_{efp_jra_sh.level.values[i].astype(np.int64)}hPa'] = efp_jra_sh.values[i].round(3)

print(f'The EFP mean: {efp_mean_jra_sh}')
print()

for key in levels_dict_jra_sh:
    print(f'The EFP for {key}: {levels_dict_jra_sh[key]}')
    print()

/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)


The EFP mean: 0.372

The EFP for efp_600hPa: 0.266

The EFP for efp_500hPa: 0.336

The EFP for efp_400hPa: 0.352

The EFP for efp_300hPa: 0.408

The EFP for efp_250hPa: 0.456

The EFP for efp_200hPa: 0.412



/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)


## ERA Interim

### Eddy Feedback Parameter

In [10]:
r_era = ef.calculate_efp_latitude(era, level_mean=False, which_div1='div1_pr')

efp_mean_era = ef.calculate_efp(era, which_div1='div1_pr').round(3)
efp_era = ef.calculate_efp(era, take_level_mean=False, which_div1='div1_pr')
efp_era

<xarray.DataArray (level: 6)>
array([0.38470769, 0.47740681, 0.47941823, 0.49745925, 0.49563176,
       0.39322539])
Coordinates:
  * level    (level) float32 600.0 500.0 400.0 300.0 250.0 200.0

In [11]:
levels_dict_era = {}
for i in range(len(r_era.level.values)):

    levels_dict_era[f'efp_{efp_era.level.values[i].astype(np.int64)}hPa'] = efp_era.values[i].round(3)

print(f'The EFP mean: {efp_mean_era}')
print()

for key in levels_dict_era:
    print(f'The EFP for {key}: {levels_dict_era[key]}')
    print()

The EFP mean: 0.455

The EFP for efp_600hPa: 0.385

The EFP for efp_500hPa: 0.477

The EFP for efp_400hPa: 0.479

The EFP for efp_300hPa: 0.497

The EFP for efp_250hPa: 0.496

The EFP for efp_200hPa: 0.393



### Southern Hemisphere

In [12]:
r_era_sh = ef.calculate_efp_latitude(era, level_mean=False, which_div1='div1_pr', calc_south_hemis=True)
efp_mean_era_sh = ef.calculate_efp(era, calc_south_hemis=True, which_div1='div1_pr').round(3)
efp_era_sh = ef.calculate_efp(era, take_level_mean=False, calc_south_hemis=True, which_div1='div1_pr')

/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)


In [13]:
levels_dict_era_sh = {}
for i in range(len(r_era_sh.level.values)):

    levels_dict_era_sh[f'efp_{efp_era_sh.level.values[i].astype(np.int64)}hPa'] = efp_era_sh.values[i].round(3)

print(f'The EFP mean: {efp_mean_era_sh}')
print()

for key in levels_dict_era_sh:
    print(f'The EFP for {key}: {levels_dict_era_sh[key]}')
    print()

The EFP mean: 0.389

The EFP for efp_600hPa: 0.275

The EFP for efp_500hPa: 0.346

The EFP for efp_400hPa: 0.38

The EFP for efp_300hPa: 0.44

The EFP for efp_250hPa: 0.475

The EFP for efp_200hPa: 0.42



/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/num

## NCEP-NCAR

### Eddy Feedback Parameter

In [14]:
r_ncep = ef.calculate_efp_latitude(ncep, level_mean=False, which_div1='div1_pr')

efp_mean_ncep = ef.calculate_efp(ncep, which_div1='div1_pr').round(3)
efp_ncep = ef.calculate_efp(ncep, take_level_mean=False, which_div1='div1_pr')
efp_ncep

<xarray.DataArray (level: 6)>
array([0.33567809, 0.4278452 , 0.46236303, 0.50153344, 0.4939213 ,
       0.44448473])
Coordinates:
  * level    (level) float32 600.0 500.0 400.0 300.0 250.0 200.0

In [15]:
levels_dict_ncep = {}
for i in range(len(r_ncep.level.values)):

    levels_dict_ncep[f'efp_{efp_ncep.level.values[i].astype(np.int64)}hPa'] = efp_ncep.values[i].round(3)

print(f'The EFP mean: {efp_mean_ncep}')
print()

for key in levels_dict_ncep:
    print(f'The EFP for {key}: {levels_dict_ncep[key]}')
    print()

The EFP mean: 0.444

The EFP for efp_600hPa: 0.336

The EFP for efp_500hPa: 0.428

The EFP for efp_400hPa: 0.462

The EFP for efp_300hPa: 0.502

The EFP for efp_250hPa: 0.494

The EFP for efp_200hPa: 0.444



### Southern Hemisphere

In [16]:
r_ncep_sh = ef.calculate_efp_latitude(ncep, level_mean=False, which_div1='div1_pr', calc_south_hemis=True)
efp_mean_ncep_sh = ef.calculate_efp(ncep, calc_south_hemis=True, which_div1='div1_pr').round(3)
efp_ncep_sh = ef.calculate_efp(ncep, take_level_mean=False, calc_south_hemis=True, which_div1='div1_pr')

/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)


In [17]:
levels_dict_ncep_sh = {}
for i in range(len(r_ncep_sh.level.values)):

    levels_dict_ncep_sh[f'efp_{efp_ncep_sh.level.values[i].astype(np.int64)}hPa'] = efp_ncep_sh.values[i].round(3)

print(f'The EFP mean: {efp_mean_ncep_sh}')
print()

for key in levels_dict_ncep_sh:
    print(f'The EFP for {key}: {levels_dict_ncep_sh[key]}')
    print()

The EFP mean: 0.261

The EFP for efp_600hPa: 0.203

The EFP for efp_500hPa: 0.236

The EFP for efp_400hPa: 0.239

The EFP for efp_300hPa: 0.282

The EFP for efp_250hPa: 0.305

The EFP for efp_200hPa: 0.299



/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/num

# QG vs Primitive

In [18]:
efp_jra_pr = ef.calculate_efp(jra, which_div1='div1_pr')
efp_jra_qg = ef.calculate_efp(jra, which_div1='div1_qg')

print(efp_jra_pr)
print(efp_jra_qg)

0.4484
0.4183


In [19]:
efp_era_pr = ef.calculate_efp(era, which_div1='div1_pr')
efp_era_qg = ef.calculate_efp(era, which_div1='div1_qg')

print(efp_era_pr)
print(efp_era_qg)

0.4546
0.4207


In [20]:
efp_ncep_pr = ef.calculate_efp(ncep, which_div1='div1_pr')
efp_ncep_qg = ef.calculate_efp(ncep, which_div1='div1_qg')

print(efp_ncep_pr)
print(efp_ncep_qg)

0.4443
0.4283


## JRA55

In [21]:
r_jra = ef.calculate_efp_latitude(jra, level_mean=False, which_div1='div1_qg')
efp_mean_jra = ef.calculate_efp(jra, which_div1='div1_qg').round(3)
efp_jra = ef.calculate_efp(jra, take_level_mean=False, which_div1='div1_qg')
efp_jra

<xarray.DataArray (level: 6)>
array([0.26096607, 0.3760757 , 0.43591299, 0.52482782, 0.51024082,
       0.40184186])
Coordinates:
  * level    (level) float32 600.0 500.0 400.0 300.0 250.0 200.0

In [22]:
levels_dict_jra = {}
for i in range(len(r_jra.level.values)):

    levels_dict_jra[f'efp_{efp_jra.level.values[i].astype(np.int64)}hPa'] = efp_jra.values[i].round(3)

print(f'The EFP mean: {efp_mean_jra}')
print()

for key in levels_dict_jra:
    print(f'The EFP for {key}: {levels_dict_jra[key]}')
    print()

The EFP mean: 0.418

The EFP for efp_600hPa: 0.261

The EFP for efp_500hPa: 0.376

The EFP for efp_400hPa: 0.436

The EFP for efp_300hPa: 0.525

The EFP for efp_250hPa: 0.51

The EFP for efp_200hPa: 0.402



### Southern Hemisphere

In [23]:
r_jra_sh = ef.calculate_efp_latitude(jra, level_mean=False, which_div1='div1_qg', calc_south_hemis=True)
efp_mean_jra_sh = ef.calculate_efp(jra, calc_south_hemis=True, which_div1='div1_qg').round(3)
efp_jra_sh = ef.calculate_efp(jra, take_level_mean=False, calc_south_hemis=True, which_div1='div1_qg')

/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)


In [24]:
levels_dict_jra_sh = {}
for i in range(len(r_jra_sh.level.values)):

    levels_dict_jra_sh[f'efp_{efp_jra_sh.level.values[i].astype(np.int64)}hPa'] = efp_jra_sh.values[i].round(3)

print(f'The EFP mean: {efp_mean_jra_sh}')
print()

for key in levels_dict_jra_sh:
    print(f'The EFP for {key}: {levels_dict_jra_sh[key]}')
    print()

/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)


The EFP mean: 0.346

The EFP for efp_600hPa: 0.203

The EFP for efp_500hPa: 0.281

The EFP for efp_400hPa: 0.338

The EFP for efp_300hPa: 0.413

The EFP for efp_250hPa: 0.445

The EFP for efp_200hPa: 0.396



/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
/home/users/cturrell/miniforge3/envs/eddy/lib/python3.12/site-packages/dask/array/numpy_compat.py:51: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
